# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/icevision_dashboards/',
                'doc_host': 'https://fstroth.github.io',
                'git_url': 'https://github.com/fstroth/icevision_dashboards/tree/master/',
                'lib_path': 'icevision_dashboards'},
  'syms': { 'icevision_dashboards.core.dashboards': {},
            'icevision_dashboards.core.data': {},
            'icevision_dashboards.dashboards': {},
            'icevision_dashboards.data': {},
            'icevision_dashboards.metrics': {},
            'icevision_dashboards.plotting.controls': {},
            'icevision_dashboards.plotting.core': {},
            'icevision_dashboards.plotting.utils': {},
            'icevision_dashboards.utils': {}}}
