# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Dashboard": "core.dashboards.ipynb",
         "Gallery": "core.dashboards.ipynb",
         "DatasetOverview": "core.dashboards.ipynb",
         "MultiDatasetOverview": "core.dashboards.ipynb",
         "DatasetComparison": "core.dashboards.ipynb",
         "DatasetFilter": "core.dashboards.ipynb",
         "DatasetFilterWithRangeSliderAndMultiSelect": "core.dashboards.ipynb",
         "ScatterDatasetFilter": "core.dashboards.ipynb",
         "DatasetGenerator": "core.dashboards.ipynb",
         "Observable": "core.data.ipynb",
         "ObservableList": "core.data.ipynb",
         "DatasetDescriptor": "core.data.ipynb",
         "StringDescriptor": "core.data.ipynb",
         "GenericDataset": "core.data.ipynb",
         "IcevisionGallery": "dashboards.ipynb",
         "ObjectDetectionDatasetOverview": "dashboards.ipynb",
         "ObjectDetectionDatasetComparison": "dashboards.ipynb",
         "ObjectDetectionDatasetGenerator": "dashboards.ipynb",
         "RecordDataframeParser": "data.ipynb",
         "BboxRecordDataframeParser": "data.ipynb",
         "MaskRecordDataframeParser": "data.ipynb",
         "RecordDataset": "data.ipynb",
         "DataDescriptorBbox": "data.ipynb",
         "StatsDesscriptorBbox": "data.ipynb",
         "ImageStatsDesscriptorBbox": "data.ipynb",
         "ClassStatsDesscriptorBbox": "data.ipynb",
         "BboxRecordDataset": "data.ipynb",
         "Filter": "plotting.controls.ipynb",
         "RangeFilter": "plotting.controls.ipynb",
         "CategoricalFilter": "plotting.controls.ipynb",
         "TimeFilter": "plotting.controls.ipynb",
         "ScatterFilter": "plotting.controls.ipynb",
         "GenericMulitScatterFilter": "plotting.controls.ipynb",
         "barplot": "plotting.core.ipynb",
         "histogram": "plotting.core.ipynb",
         "heatmap": "plotting.core.ipynb",
         "time_arc_plot": "plotting.core.ipynb",
         "table_from_dataframe": "plotting.core.ipynb",
         "stacked_hist": "plotting.core.ipynb",
         "categorical_2d_histogram": "plotting.core.ipynb",
         "categorical_2d_histogram_with_gui": "plotting.core.ipynb",
         "calculate_mixing_matrix": "plotting.utils.ipynb",
         "get_min_and_max_dates": "plotting.utils.ipynb",
         "convert_rgb_image_to_bokeh_rgb_image": "plotting.utils.ipynb",
         "draw_record_with_bokeh": "plotting.utils.ipynb"}

modules = ["core/dashboards.py",
           "core/data.py",
           "dashboards.py",
           "data.py",
           "plotting/controls.py",
           "plotting/core.py",
           "plotting/utils.py"]

doc_url = "https://fstroth.github.io/icevision_dashboards/"

git_url = "https://github.com/fstroth/icevision_dashboards/tree/master/"

def custom_doc_links(name): return None
