# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"gallery": "components.ipynb",
         "barplot_class_occurance": "components.ipynb",
         "draw_area_histogram": "components.ipynb",
         "class_area_histogram_with_select": "components.ipynb",
         "TrainValRecordsComparison": "dashboards.ipynb",
         "convert_rgb_image_to_bokeh_rgb_image": "utils.ipynb",
         "draw_record_with_bokeh": "utils.ipynb",
         "aggregate_record_data": "utils.ipynb",
         "draw_class_based_barplot": "utils.ipynb"}

modules = ["components.py",
           "dashboards.py",
           "utils.py"]

doc_url = "https://fstroth.github.io/icevision_dashboard/"

git_url = "https://github.com/fstroth/icevision_dashboard/tree/master/"

def custom_doc_links(name): return None
