# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"gallery": "components.ipynb",
         "barplot_class_occurance": "components.ipynb",
         "area_histogram": "components.ipynb",
         "histogram_with_gui": "components.ipynb",
         "DatasetFilter": "dashboards.ipynb",
         "TrainValRecordsComparison": "dashboards.ipynb",
         "aggregate_record_data": "utils.ipynb",
         "convert_rgb_image_to_bokeh_rgb_image": "utils.ipynb",
         "draw_record_with_bokeh": "utils.ipynb",
         "draw_class_based_barplot": "utils.ipynb",
         "histogram": "utils.ipynb",
         "time_arc_plot": "utils.ipynb",
         "generate_range_filter": "utils.ipynb",
         "get_min_and_max_dates": "utils.ipynb",
         "generate_creation_modification_time_filter": "utils.ipynb"}

modules = ["components.py",
           "dashboards.py",
           "utils.py"]

doc_url = "https://fstroth.github.io/icevision_dashboard/"

git_url = "https://github.com/fstroth/icevision_dashboard/tree/master/"

def custom_doc_links(name): return None
